"""baseline schema (M1-M6)

Revision ID: 92e35d3016ff
Revises: 
Create Date: 2026-08-02 18:05:43.205777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e35d3016ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('unit_system', sa.String(length=10), nullable=False),
    sa.Column('admin_levels', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('data_ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_ingestion_jobs_provider_code'), 'data_ingestion_jobs', ['provider_code'], unique=False)
    op.create_table('data_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('tos_compliant', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('economic_indicators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('indicator_name', sa.String(length=200), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'indicator_code', 'period', name='uq_economic_indicator_period')
    )
    op.create_index(op.f('ix_economic_indicators_country_code'), 'economic_indicators', ['country_code'], unique=False)
    op.create_index(op.f('ix_economic_indicators_indicator_code'), 'economic_indicators', ['indicator_code'], unique=False)
    op.create_index(op.f('ix_economic_indicators_period'), 'economic_indicators', ['period'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('administrative_areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['administrative_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'slug', name='uq_area_country_slug')
    )
    op.create_index(op.f('ix_administrative_areas_country_code'), 'administrative_areas', ['country_code'], unique=False)
    op.create_index(op.f('ix_administrative_areas_level'), 'administrative_areas', ['level'], unique=False)
    op.create_index(op.f('ix_administrative_areas_name'), 'administrative_areas', ['name'], unique=False)
    op.create_index(op.f('ix_administrative_areas_parent_id'), 'administrative_areas', ['parent_id'], unique=False)
    op.create_index(op.f('ix_administrative_areas_slug'), 'administrative_areas', ['slug'], unique=False)
    op.create_table('agencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['data_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('muted_types', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedup_key', name='uq_notification_user_dedup')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id')
    )
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('market_forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.Column('listing_type', sa.String(length=10), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_change_pct', sa.Float(), nullable=False),
    sa.Column('low_change_pct', sa.Float(), nullable=False),
    sa.Column('high_change_pct', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('drivers', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['administrative_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_forecasts_area_id'), 'market_forecasts', ['area_id'], unique=False)
    op.create_table('market_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('listing_type', sa.String(length=10), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('median_price', sa.Float(), nullable=False),
    sa.Column('avg_price_sqm', sa.Float(), nullable=False),
    sa.Column('median_price_sqm', sa.Float(), nullable=False),
    sa.Column('active_listings', sa.Integer(), nullable=False),
    sa.Column('new_listings', sa.Integer(), nullable=False),
    sa.Column('removed_listings', sa.Integer(), nullable=False),
    sa.Column('avg_days_on_market', sa.Float(), nullable=False),
    sa.Column('price_reduction_share', sa.Float(), nullable=False),
    sa.Column('avg_discount_pct', sa.Float(), nullable=False),
    sa.Column('rent_avg_sqm', sa.Float(), nullable=False),
    sa.Column('gross_yield_pct', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('data_quality', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['administrative_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'period', 'listing_type', name='uq_metric_area_period_type')
    )
    op.create_index(op.f('ix_market_metrics_area_id'), 'market_metrics', ['area_id'], unique=False)
    op.create_index(op.f('ix_market_metrics_period'), 'market_metrics', ['period'], unique=False)
    op.create_table('omi_zone_quotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('comune', sa.String(length=200), nullable=False),
    sa.Column('zone_code', sa.String(length=20), nullable=False),
    sa.Column('zone_description', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.String(length=40), nullable=False),
    sa.Column('conservation_state', sa.String(length=30), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('listing_type', sa.String(length=10), nullable=False),
    sa.Column('price_sqm_min', sa.Float(), nullable=False),
    sa.Column('price_sqm_max', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['administrative_areas.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['data_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'zone_code', 'property_type', 'conservation_state', 'period', 'listing_type', name='uq_omi_quotation_natural_key')
    )
    op.create_index(op.f('ix_omi_zone_quotations_area_id'), 'omi_zone_quotations', ['area_id'], unique=False)
    op.create_index(op.f('ix_omi_zone_quotations_period'), 'omi_zone_quotations', ['period'], unique=False)
    op.create_index(op.f('ix_omi_zone_quotations_provider_id'), 'omi_zone_quotations', ['provider_id'], unique=False)
    op.create_table('physical_properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.Column('address_text', sa.String(length=300), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('property_type', sa.String(length=40), nullable=False),
    sa.Column('size_sqm', sa.Float(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('energy_class', sa.String(length=3), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['administrative_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_properties_area_id'), 'physical_properties', ['area_id'], unique=False)
    op.create_index(op.f('ix_physical_properties_property_type'), 'physical_properties', ['property_type'], unique=False)
    op.create_table('property_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=True),
    sa.Column('source_external_id', sa.String(length=100), nullable=False),
    sa.Column('listing_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('photos_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedup_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['physical_properties.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['data_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'source_external_id', name='uq_listing_provider_ext')
    )
    op.create_index(op.f('ix_property_listings_current_price'), 'property_listings', ['current_price'], unique=False)
    op.create_index(op.f('ix_property_listings_listing_type'), 'property_listings', ['listing_type'], unique=False)
    op.create_index(op.f('ix_property_listings_property_id'), 'property_listings', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_listings_provider_id'), 'property_listings', ['provider_id'], unique=False)
    op.create_index(op.f('ix_property_listings_status'), 'property_listings', ['status'], unique=False)
    op.create_table('listing_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photos_count', sa.Integer(), nullable=False),
    sa.Column('size_sqm', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('energy_class', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('snapshot_key', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['property_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'version_number', name='uq_version_listing_number')
    )
    op.create_index(op.f('ix_listing_versions_listing_id'), 'listing_versions', ['listing_id'], unique=False)
    op.create_table('price_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['property_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_observations_listing_id'), 'price_observations', ['listing_id'], unique=False)
    op.create_table('valuations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('range_low', sa.Float(), nullable=False),
    sa.Column('range_high', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('n_comparables', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['property_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_listing_id'), 'valuations', ['listing_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('area_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('initial_price', sa.Float(), nullable=True),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['administrative_areas.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['property_listings.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_area_id'), 'watchlist_items', ['area_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_listing_id'), 'watchlist_items', ['listing_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_listing_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_area_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_valuations_listing_id'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_index(op.f('ix_price_observations_listing_id'), table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index(op.f('ix_listing_versions_listing_id'), table_name='listing_versions')
    op.drop_table('listing_versions')
    op.drop_index(op.f('ix_property_listings_status'), table_name='property_listings')
    op.drop_index(op.f('ix_property_listings_provider_id'), table_name='property_listings')
    op.drop_index(op.f('ix_property_listings_property_id'), table_name='property_listings')
    op.drop_index(op.f('ix_property_listings_listing_type'), table_name='property_listings')
    op.drop_index(op.f('ix_property_listings_current_price'), table_name='property_listings')
    op.drop_table('property_listings')
    op.drop_index(op.f('ix_physical_properties_property_type'), table_name='physical_properties')
    op.drop_index(op.f('ix_physical_properties_area_id'), table_name='physical_properties')
    op.drop_table('physical_properties')
    op.drop_index(op.f('ix_omi_zone_quotations_provider_id'), table_name='omi_zone_quotations')
    op.drop_index(op.f('ix_omi_zone_quotations_period'), table_name='omi_zone_quotations')
    op.drop_index(op.f('ix_omi_zone_quotations_area_id'), table_name='omi_zone_quotations')
    op.drop_table('omi_zone_quotations')
    op.drop_index(op.f('ix_market_metrics_period'), table_name='market_metrics')
    op.drop_index(op.f('ix_market_metrics_area_id'), table_name='market_metrics')
    op.drop_table('market_metrics')
    op.drop_index(op.f('ix_market_forecasts_area_id'), table_name='market_forecasts')
    op.drop_table('market_forecasts')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_hash'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_table('agencies')
    op.drop_index(op.f('ix_administrative_areas_slug'), table_name='administrative_areas')
    op.drop_index(op.f('ix_administrative_areas_parent_id'), table_name='administrative_areas')
    op.drop_index(op.f('ix_administrative_areas_name'), table_name='administrative_areas')
    op.drop_index(op.f('ix_administrative_areas_level'), table_name='administrative_areas')
    op.drop_index(op.f('ix_administrative_areas_country_code'), table_name='administrative_areas')
    op.drop_table('administrative_areas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_economic_indicators_period'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_indicator_code'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_country_code'), table_name='economic_indicators')
    op.drop_table('economic_indicators')
    op.drop_table('data_providers')
    op.drop_index(op.f('ix_data_ingestion_jobs_provider_code'), table_name='data_ingestion_jobs')
    op.drop_table('data_ingestion_jobs')
    op.drop_table('countries')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
